/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI.NhanKhauView;

import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyNhanKhauCtrl.NhanKhauCtrl;
import com.nhom71_quanlyhokhau.models.NhanKhau;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class NhanKhauHomeView extends javax.swing.JPanel {

    /**
     * Creates new form NhanKhauHomeView
     */
    public NhanKhauHomeView() throws SQLException, ClassNotFoundException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextTimKiemMaNK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNhanKhau = new javax.swing.JTable();
        jButtonThemNhanKhau = new javax.swing.JButton();
        jButtonDkTamVang = new javax.swing.JButton();
        jButtonDkTamTru = new javax.swing.JButton();
        jButtonKhaiTu = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextTimKiemMaNK.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm theo mã Nhân Khẩu:");

        jButtonTimKiem.setBackground(new java.awt.Color(255, 255, 153));
        jButtonTimKiem.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jTableNhanKhau.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTableNhanKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ"
            }
        ));
        danhsachnhankhau = (DefaultTableModel) jTableNhanKhau.getModel();
        TableCellEditor nonEditableCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhsachnhankhau.getColumnCount(); column++) {
            TableColumn tableColumn = jTableNhanKhau.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor);
        }
        jTableNhanKhau.setToolTipText("");
        jTableNhanKhau.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableNhanKhau.setFocusable(false);
        jTableNhanKhau.setRowHeight(30);
        jTableNhanKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTableNhanKhauMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableNhanKhauMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableNhanKhau);

        jButtonThemNhanKhau.setBackground(new java.awt.Color(255, 255, 153));
        jButtonThemNhanKhau.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonThemNhanKhau.setText("Thêm Nhân Khẩu");
        jButtonThemNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemNhanKhauActionPerformed(evt);
            }
        });

        jButtonDkTamVang.setBackground(new java.awt.Color(255, 255, 153));
        jButtonDkTamVang.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonDkTamVang.setText("Đăng ký Tạm Vắng");
        jButtonDkTamVang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDkTamVangActionPerformed(evt);
            }
        });

        jButtonDkTamTru.setBackground(new java.awt.Color(255, 255, 153));
        jButtonDkTamTru.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonDkTamTru.setText("Đăng ký Tạm Trú");
        jButtonDkTamTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDkTamTruActionPerformed(evt);
            }
        });

        jButtonKhaiTu.setBackground(new java.awt.Color(255, 255, 153));
        jButtonKhaiTu.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonKhaiTu.setText("Khai Tử");
        jButtonKhaiTu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhaiTuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTimKiemMaNK, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTimKiem))
                            .addComponent(jLabel1))
                        .addContainerGap(672, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDkTamVang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThemNhanKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDkTamTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonKhaiTu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTimKiemMaNK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonThemNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDkTamVang, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDkTamTru, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKhaiTu, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loadData() throws SQLException, ClassNotFoundException {
        if (danhsachnhankhau.getRowCount()>0) danhsachnhankhau.setRowCount(0);
        NhanKhauCtrl nhanKhauCtrl = new NhanKhauCtrl();
        List<NhanKhau> nhanKhauList = nhanKhauCtrl.getDanhSachNhanKhau();

        for (int i = 0; i<nhanKhauList.size(); i++) {
            int id = nhanKhauList.get(i).getId();
            String hoTen = nhanKhauList.get(i).getHoTen();
            String ngaySinh = nhanKhauList.get(i).getNgaySinh();
            String gioiTinh = nhanKhauList.get(i).getGioiTinh();
            String diaChi = nhanKhauList.get(i).getDiaChiHienTai();

            Object[] row = {id, hoTen, gioiTinh, ngaySinh, diaChi};
            danhsachnhankhau.addRow(row);
        }
    }
    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonThemNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemNhanKhauActionPerformed
        // TODO add your handling code here:
        ThemNhanKhauView themNhanKhauView = new ThemNhanKhauView();
        themNhanKhauView.setVisible(true);
    }//GEN-LAST:event_jButtonThemNhanKhauActionPerformed

    private void jButtonDkTamVangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDkTamVangActionPerformed
        // TODO add your handling code here:
        TamVangView tamVangView = new TamVangView();
        tamVangView.setVisible(true);
    }//GEN-LAST:event_jButtonDkTamVangActionPerformed

    private void jButtonDkTamTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDkTamTruActionPerformed
        // TODO add your handling code here:
        TamTruView tamTruView = new TamTruView();
        tamTruView.setVisible(true);
    }//GEN-LAST:event_jButtonDkTamTruActionPerformed

    private void jButtonKhaiTuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhaiTuActionPerformed
        // TODO add your handling code here:
        KhaiTuView khaiTuView = new KhaiTuView();
        khaiTuView.setVisible(true);
    }//GEN-LAST:event_jButtonKhaiTuActionPerformed

    private void jTableNhanKhauMouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTableNhanKhauMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            int row = jTableNhanKhau.getSelectedRow();
            int IdNhanKhau = (int) jTableNhanKhau.getValueAt(row, 0);
            System.out.println(IdNhanKhau);
            ThongTinChiTietNhanKhau thongTinChiTietNhanKhau = new ThongTinChiTietNhanKhau(IdNhanKhau);
            thongTinChiTietNhanKhau.setVisible(true);
        }
    }//GEN-LAST:event_jTableNhanKhauMouseClicked

    private void jTableNhanKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNhanKhauMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableNhanKhauMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDkTamTru;
    private javax.swing.JButton jButtonDkTamVang;
    private javax.swing.JButton jButtonKhaiTu;
    private javax.swing.JButton jButtonThemNhanKhau;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNhanKhau;
    private javax.swing.JTextField jTextTimKiemMaNK;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel danhsachnhankhau;
}
