/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI.HoKhauView;

import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyHoKhauCtrl.CheckNhanKhauThuocHoKhau;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyNhanKhauCtrl.NhanKhauCtrl;
import com.nhom71_quanlyhokhau.models.NhanKhau;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class DanhSachThanhVienTable extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachThanhVienTable
     */
    public DanhSachThanhVienTable() throws SQLException, ClassNotFoundException {
        initComponents();
        loadData();
        setLocationRelativeTo(null);
    }
    public DanhSachThanhVienTable(String button) throws SQLException, ClassNotFoundException {
        this.button = button;
        initComponents();
        loadData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ tên", "Giới tính", "Ngày sinh"
            }
        ));
        danhsachnhankhau = (DefaultTableModel) jTable1.getModel();
        TableCellEditor nonEditableCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhsachnhankhau.getColumnCount(); column++) {
            TableColumn tableColumn = jTable1.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor);
        }
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(30);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTable1MouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() throws SQLException, ClassNotFoundException {
        if (danhsachnhankhau.getRowCount()>0) danhsachnhankhau.setRowCount(0);
        NhanKhauCtrl nhanKhauCtrl = new NhanKhauCtrl();
        List<NhanKhau> nhanKhauList = nhanKhauCtrl.getDanhSachNhanKhau();

        for (int i = 0; i<nhanKhauList.size(); i++) {
            int id = nhanKhauList.get(i).getId();
            String hoTen = nhanKhauList.get(i).getHoTen();
            String ngaySinh = nhanKhauList.get(i).getNgaySinh();
            String gioiTinh = nhanKhauList.get(i).getGioiTinh();

            Object[] row = {id, hoTen, gioiTinh, ngaySinh};
            danhsachnhankhau.addRow(row);
        }
    }
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2 && button == "Chọn") {
            int row = jTable1.getSelectedRow();

            NhanKhau nhanKhau = new NhanKhau();
            nhanKhau.setId((int) jTable1.getValueAt(row, 0));
            nhanKhau.setHoTen((String) jTable1.getValueAt(row, 1));
            nhanKhau.setGioiTinh((String) jTable1.getValueAt(row, 2));
            nhanKhau.setNgaySinh((String) jTable1.getValueAt(row, 3));

            if (CheckNhanKhauThuocHoKhau.isDaCoHoKhau(nhanKhau)) return;
            ThemHoKhauView.changeChuHo(nhanKhau);
            dispose();
        }

        if (evt.getClickCount()==2 && button == "Thêm") {
            int row = jTable1.getSelectedRow();

            NhanKhau nhanKhau = new NhanKhau();
            nhanKhau.setId((int) jTable1.getValueAt(row, 0));
            nhanKhau.setHoTen((String) jTable1.getValueAt(row, 1));
            nhanKhau.setGioiTinh((String) jTable1.getValueAt(row, 2));
            nhanKhau.setNgaySinh((String) jTable1.getValueAt(row, 3));

            if (CheckNhanKhauThuocHoKhau.isDaCoHoKhau(nhanKhau)) return;
            if (nhanKhau.getId() == ThemHoKhauView.getChuHo().getId()) {
                JOptionPane.showMessageDialog(null, "Nhân khẩu đang được chọn làm chủ hộ");
                return;
            }
            ThemHoKhauView.addNhanKhau(nhanKhau);
            ThemHoKhauView.loadTable();
            dispose();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel danhsachnhankhau;
    private String button;
}
