/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI.HoKhauView;

import com.nhom71_quanlyhokhau.Bean.QuanLyHoKhauBean.HoKhauBean;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyHoKhauCtrl.HoKhauCtrl;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyNhanKhauCtrl.NhanKhauCtrl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class HoKhauHomeView extends javax.swing.JPanel {

    /**
     * Creates new form HoKhauHomeView
     */
    public HoKhauHomeView() throws SQLException, ClassNotFoundException {
        hoKhauBeanList = new ArrayList<>();
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextTimKiemMaHK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHoKhau = new javax.swing.JTable();
        jButtonThemHoKhau = new javax.swing.JButton();
        jButtonTachHoKhau = new javax.swing.JButton();
        jButtonTimKiem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTextTimKiemMaHK.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm theo mã Hộ Khẩu:");

        jTableHoKhau.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTableHoKhau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Hộ khẩu","Mã Hộ khẩu", "Tên chủ hộ","Giới tính", "Mã khu vực", "Địa chỉ"
            }
        ));
        danhSachHoKhau = (DefaultTableModel) jTableHoKhau.getModel();
        TableCellEditor nonEditableCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachHoKhau.getColumnCount(); column++) {
            TableColumn tableColumn = jTableHoKhau.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor);
        }
        jTableHoKhau.setToolTipText("");
        jTableHoKhau.setRowHeight(30);
        jTableHoKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTableHoKhauMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableHoKhauMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableHoKhau);

        jButtonThemHoKhau.setBackground(new java.awt.Color(255, 255, 153));
        jButtonThemHoKhau.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonThemHoKhau.setText("Thêm Hộ Khẩu");
        jButtonThemHoKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemHoKhauActionPerformed(evt);
            }
        });

        jButtonTachHoKhau.setBackground(new java.awt.Color(255, 255, 153));
        jButtonTachHoKhau.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonTachHoKhau.setText("Tách Hộ Khẩu");
        jButtonTachHoKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonTachHoKhauActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonTimKiem.setBackground(new java.awt.Color(255, 255, 153));
        jButtonTimKiem.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTimKiemMaHK, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTimKiem))
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonTachHoKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThemHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextTimKiemMaHK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonThemHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTachHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() throws SQLException, ClassNotFoundException {
        HoKhauCtrl hoKhauCtrl = new HoKhauCtrl();
        NhanKhauCtrl nhanKhauCtrl = new NhanKhauCtrl();
        hoKhauBeanList = hoKhauCtrl.getDanhSachHoKhau();

        for (int i = 0; i< hoKhauBeanList.size(); i++) {
            int idHoKhau = hoKhauBeanList.get(i).getHoKhau().getId();
            String maHoKhau = hoKhauBeanList.get(i).getHoKhau().getMaHoKhau();
            String hoTen = hoKhauBeanList.get(i).getChuHo().getHoTen();
            String gioiTinh = hoKhauBeanList.get(i).getChuHo().getGioiTinh();
            String maKhuVuc = hoKhauBeanList.get(i).getHoKhau().getMaKhuVuc();
            String diaChi = hoKhauBeanList.get(i).getHoKhau().getDiaChi();

            Object[] row = {idHoKhau,maHoKhau, hoTen, gioiTinh, maKhuVuc, diaChi};
            danhSachHoKhau.addRow(row);
        }
    }
    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jButtonThemHoKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemHoKhauActionPerformed
        // TODO add your handling code here:
        ThemHoKhauView themHoKhauView = new ThemHoKhauView();
        themHoKhauView.setVisible(true);
    }//GEN-LAST:event_jButtonThemHoKhauActionPerformed

    private void jButtonTachHoKhauActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonTachHoKhauActionPerformed
        // TODO add your handling code here:
        TachHoKhauView tachHoKhauView = new TachHoKhauView();
        tachHoKhauView.setVisible(true);
    }//GEN-LAST:event_jButtonTachHoKhauActionPerformed

    private void jTableHoKhauMouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTableHoKhauMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            int row = jTableHoKhau.getSelectedRow();
            int IdHoKhau = (int) jTableHoKhau.getValueAt(row, 0);
            ThongTinChiTietHoKhau thongTinChiTietHoKhau = new ThongTinChiTietHoKhau(IdHoKhau);
            thongTinChiTietHoKhau.setVisible(true);
        }
    }//GEN-LAST:event_jTableHoKhauMouseClicked

    private void jTableHoKhauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableHoKhauMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableHoKhauMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTachHoKhau;
    private javax.swing.JButton jButtonThemHoKhau;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHoKhau;
    private javax.swing.JTextField jTextTimKiemMaHK;
    // End of variables declaration//GEN-END:variables
    private List<HoKhauBean> hoKhauBeanList;
    private DefaultTableModel danhSachHoKhau;
}
