/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI.QuanLyCovid.KhaiBaoYTeView;

import com.nhom71_quanlyhokhau.Bean.QuanLyCovidBean.KhaiBaoBean;
import com.nhom71_quanlyhokhau.Bean.QuanLyHoKhauBean.NhanKhauBean;
import com.nhom71_quanlyhokhau.Util.DateForm;
import com.nhom71_quanlyhokhau.controllers.QuanLyCovidCtrl.QuanLyKhaiBaoCtrl.ThemKhaiBaoCtrl;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyNhanKhauCtrl.CheckCccdCtrl;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyNhanKhauCtrl.NhanKhauCtrl;
import com.nhom71_quanlyhokhau.models.KhaiBao;
import com.nhom71_quanlyhokhau.models.LichTrinh;
import com.nhom71_quanlyhokhau.models.NhanKhau;
import com.nhom71_quanlyhokhau.models.TrieuChung;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class KhaiBaoFormView extends javax.swing.JFrame {

    /**
     * Creates new form KhaiBaoFormView
     */
    public KhaiBaoFormView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextCCCD = new javax.swing.JTextField();
        jButtonCheck = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextIdNhanKhau = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextIdHoTen = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextIdGioiTinh = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextIdNgaySinh = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextIdSdt = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextIdNoiOHienTai = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jCheckBoxSot = new javax.swing.JCheckBox();
        jCheckHo = new javax.swing.JCheckBox();
        jCheckKhoTho = new javax.swing.JCheckBox();
        jCheckViemPhoi = new javax.swing.JCheckBox();
        jCheckDauHong = new javax.swing.JCheckBox();
        jCheckMetMoi = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLichTrinh = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jButtonLuu = new javax.swing.JButton();
        jButtonHuy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Khai báo y tế");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel16.setText("CMND / CCCD:");

        jButtonCheck.setBackground(new java.awt.Color(255, 255, 153));
        jButtonCheck.setText("CHECK");
        jButtonCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonCheckActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel17.setText("ID Nhân khẩu:");

        jTextIdNhanKhau.setEditable(false);
        jTextIdNhanKhau.setBackground(new java.awt.Color(255, 255, 255));
        jTextIdNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdNhanKhauActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel18.setText("Họ tên:");

        jTextIdHoTen.setEditable(false);
        jTextIdHoTen.setBackground(new java.awt.Color(255, 255, 255));
        jTextIdHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdHoTenActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel19.setText("Giới tính");

        jTextIdGioiTinh.setEditable(false);
        jTextIdGioiTinh.setBackground(new java.awt.Color(255, 255, 255));
        jTextIdGioiTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdGioiTinhActionPerformed(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel20.setText("Ngày sinh:");

        jTextIdNgaySinh.setEditable(false);
        jTextIdNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        jTextIdNgaySinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdNgaySinhActionPerformed(evt);
            }
        });

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel21.setText("Số điện thoại:");

        jTextIdSdt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdSdtActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel22.setText("Nơi ở hiện tại:");

        jTextIdNoiOHienTai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdNoiOHienTaiActionPerformed(evt);
            }
        });

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel23.setText("Các biểu hiện trong 14 ngày qua:");

        jCheckBoxSot.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxSot.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckBoxSot.setText("Sốt");

        jCheckHo.setBackground(new java.awt.Color(255, 255, 255));
        jCheckHo.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckHo.setText("Ho");

        jCheckKhoTho.setBackground(new java.awt.Color(255, 255, 255));
        jCheckKhoTho.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckKhoTho.setText("Khó thở");

        jCheckViemPhoi.setBackground(new java.awt.Color(255, 255, 255));
        jCheckViemPhoi.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckViemPhoi.setText("Viêm phổi");

        jCheckDauHong.setBackground(new java.awt.Color(255, 255, 255));
        jCheckDauHong.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckDauHong.setText("Đau họng");

        jCheckMetMoi.setBackground(new java.awt.Color(255, 255, 255));
        jCheckMetMoi.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jCheckMetMoi.setText("Mệt mỏi");

        jTableLichTrinh.setFont(new java.awt.Font("Liberation Sans", 0, 17)); // NOI18N
        jTableLichTrinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Ngày", "Địa điểm di chuyển"
            }
        ));
        danhSachLichTrinh = (DefaultTableModel) jTableLichTrinh.getModel();
        jTableLichTrinh.setRowHeight(30);
        jTableLichTrinh.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(jTableLichTrinh);
        if (jTableLichTrinh.getColumnModel().getColumnCount() > 0) {
            jTableLichTrinh.getColumnModel().getColumn(0).setMinWidth(200);
            jTableLichTrinh.getColumnModel().getColumn(0).setPreferredWidth(70);
            jTableLichTrinh.getColumnModel().getColumn(0).setMaxWidth(200);
        }

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel24.setText("Lịch trình di chuyển:");

        jButtonLuu.setBackground(new java.awt.Color(255, 255, 153));
        jButtonLuu.setText("Lưu");
        jButtonLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonLuuActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonHuy.setBackground(new java.awt.Color(255, 255, 204));
        jButtonHuy.setText("Hủy");
        jButtonHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jButtonHuy)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonLuu))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jTextIdNoiOHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jTextIdSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(38, 38, 38)
                                            .addComponent(jTextIdNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(38, 38, 38)
                                                .addComponent(jTextIdGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel16))
                                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jTextIdHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                                        .addComponent(jTextCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(jButtonCheck))
                                                    .addComponent(jTextIdNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(103, 103, 103)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCheckHo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckBoxSot, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckKhoTho, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckViemPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckDauHong, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jCheckMetMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxSot, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckHo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckKhoTho, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckViemPhoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckDauHong, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextIdNoiOHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckMetMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCheckActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonCheckActionPerformed
        // TODO add your handling code here:
        String cccd = jTextCCCD.getText();
        if (CheckCccdCtrl.returnNhanKhau(cccd) == 0) return;
        int idNhanKhau = CheckCccdCtrl.returnNhanKhau(cccd);

        NhanKhauCtrl nhanKhauCtrl = new NhanKhauCtrl();
        NhanKhauBean nhanKhauBean = nhanKhauCtrl.getChiTietNhanKhau(idNhanKhau);

        jTextIdNhanKhau.setText(String.valueOf(nhanKhauBean.getNhanKhau().getId()));
        jTextIdHoTen.setText(nhanKhauBean.getNhanKhau().getHoTen());
        jTextIdGioiTinh.setText(nhanKhauBean.getNhanKhau().getGioiTinh());
        jTextIdNgaySinh.setText(nhanKhauBean.getNhanKhau().getNgaySinh());


    }//GEN-LAST:event_jButtonCheckActionPerformed

    private void jTextIdNhanKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdNhanKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdNhanKhauActionPerformed

    private void jTextIdHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdHoTenActionPerformed

    private void jTextIdGioiTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdGioiTinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdGioiTinhActionPerformed

    private void jTextIdNgaySinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdNgaySinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdNgaySinhActionPerformed

    private void jTextIdSdtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdSdtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdSdtActionPerformed

    private void jTextIdNoiOHienTaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdNoiOHienTaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdNoiOHienTaiActionPerformed

    private void jButtonLuuActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonLuuActionPerformed
        // TODO add your handling code here:
        if (    jTextIdHoTen.getText().isEmpty()
            ||  jTextIdSdt.getText().isEmpty()
            ||  jTextIdNoiOHienTai.getText().isEmpty()
        ) {
            JOptionPane.showMessageDialog(null, "Hãy nhập đủ thông tin");
            return;
        }

        KhaiBaoBean khaiBaoBean = new KhaiBaoBean();
        KhaiBao khaiBao = new KhaiBao();
        TrieuChung trieuChung = new TrieuChung();
        List<LichTrinh> lichTrinhList = new ArrayList<>();
        NhanKhau nhanKhau = new NhanKhau();

        khaiBao.setIdNhanKhau(Integer.parseInt(jTextIdNhanKhau.getText()));
        khaiBao.setSoDienThoai(jTextIdSdt.getText());
        khaiBao.setNoiOHienTai(jTextIdNoiOHienTai.getText());
        khaiBaoBean.setKhaiBao(khaiBao);

        nhanKhau.setId(Integer.parseInt(jTextIdNhanKhau.getText()));
        khaiBaoBean.setNhanKhau(nhanKhau);

        String bieuHienBenh = "";
        if (jCheckBoxSot.isSelected()) bieuHienBenh+= "Sốt, ";
        if (jCheckHo.isSelected()) bieuHienBenh+= "Ho, ";
        if (jCheckKhoTho.isSelected()) bieuHienBenh+= "Khó thở, ";
        if (jCheckViemPhoi.isSelected()) bieuHienBenh+= "Viêm phổi, ";
        if (jCheckDauHong.isSelected()) bieuHienBenh+= "Đau họng, ";
        if (jCheckMetMoi.isSelected()) bieuHienBenh+= "Mệt mỏi, ";
        String trieuChungInput = "";
        if (!bieuHienBenh.isEmpty()) trieuChungInput = bieuHienBenh.substring(0, bieuHienBenh.length() - 2);
        trieuChung.setBieuHien(trieuChungInput);
        khaiBaoBean.setTrieuChung(trieuChung);

        for (int i = 0; i<danhSachLichTrinh.getRowCount(); i++) {
            if (danhSachLichTrinh.getValueAt(i, 0) == null) break;
            LichTrinh lichTrinh = new LichTrinh();
            lichTrinh.setNgay((String) danhSachLichTrinh.getValueAt(i, 0));
            lichTrinh.setNoiDung((String) danhSachLichTrinh.getValueAt(i, 1));

            lichTrinhList.add(lichTrinh);
        }
        khaiBaoBean.setLichTrinhList(lichTrinhList);

        ThemKhaiBaoCtrl themKhaiBaoCtrl = new ThemKhaiBaoCtrl();
        if (themKhaiBaoCtrl.addNewKhaiBao(khaiBaoBean)) {
            JOptionPane.showMessageDialog(null, "Thêm thành công");
            dispose();
        }
        return;
    }//GEN-LAST:event_jButtonLuuActionPerformed

    private void jButtonHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuyActionPerformed
        // TODO add your handling code here:
        int confirmResult = JOptionPane.showConfirmDialog(null, "Xác nhận Thoát?", "Thoát", JOptionPane.YES_NO_OPTION);
        if (confirmResult == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_jButtonHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCheck;
    private javax.swing.JButton jButtonHuy;
    private javax.swing.JButton jButtonLuu;
    private javax.swing.JCheckBox jCheckBoxSot;
    private javax.swing.JCheckBox jCheckDauHong;
    private javax.swing.JCheckBox jCheckHo;
    private javax.swing.JCheckBox jCheckKhoTho;
    private javax.swing.JCheckBox jCheckMetMoi;
    private javax.swing.JCheckBox jCheckViemPhoi;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLichTrinh;
    private javax.swing.JTextField jTextCCCD;
    private javax.swing.JTextField jTextIdGioiTinh;
    private javax.swing.JTextField jTextIdHoTen;
    private javax.swing.JTextField jTextIdNgaySinh;
    private javax.swing.JTextField jTextIdNhanKhau;
    private javax.swing.JTextField jTextIdNoiOHienTai;
    private javax.swing.JTextField jTextIdSdt;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel danhSachLichTrinh;
}
