/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI.QuanLyCovid.KhaiBaoYTeView;

import com.nhom71_quanlyhokhau.Bean.QuanLyCovidBean.KhaiBaoBean;
import com.nhom71_quanlyhokhau.controllers.CovidHomeCtrl;
import com.nhom71_quanlyhokhau.controllers.QuanLyCovidCtrl.QuanLyKhaiBaoCtrl.KhaiBaoCtrl;
import com.nhom71_quanlyhokhau.models.KhaiBao;
import com.nhom71_quanlyhokhau.models.NhanKhau;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class KhaiBaoYTePanel extends javax.swing.JPanel {

    /**
     * Creates new form KhaiBaoYTePanel
     */
    public KhaiBaoYTePanel() throws SQLException, ClassNotFoundException {

        initComponents();
        loadData();
        CovidHomeCtrl covidHomeCtrl = new CovidHomeCtrl();
        String daKhaiBao = covidHomeCtrl.getSoDaKhaiBao() +" / "+covidHomeCtrl.getTongNhanKhau();
        jLabelSoKhaiBao.setText(daKhaiBao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextTimKiemMaNK = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonTimKiem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKhaiBaoYTe = new javax.swing.JTable();
        jButtonKhaiBaoYTe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelDaKhaiBao = new javax.swing.JLabel();
        jLabelSoKhaiBao = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextTimKiemMaNK.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Tìm kiếm theo mã Nhân Khẩu:");

        jButtonTimKiem.setBackground(new java.awt.Color(255, 255, 153));
        jButtonTimKiem.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTimKiemActionPerformed(evt);
            }
        });

        jTableKhaiBaoYTe.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTableKhaiBaoYTe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Tờ khai", "Họ tên", "Giới tính", "Ngày sinh", "Ngày khai báo"
            }
        ));
        danhSach = (DefaultTableModel) jTableKhaiBaoYTe.getModel();
        TableCellEditor nonEditableCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSach.getColumnCount(); column++) {
            TableColumn tableColumn = jTableKhaiBaoYTe.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor);
        }
        jTableKhaiBaoYTe.setToolTipText("");
        jTableKhaiBaoYTe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableKhaiBaoYTe.setFocusable(false);
        jTableKhaiBaoYTe.setRowHeight(30);
        jTableKhaiBaoYTe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTableKhaiBaoYTeMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableKhaiBaoYTeMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableKhaiBaoYTe);

        jButtonKhaiBaoYTe.setBackground(new java.awt.Color(255, 255, 153));
        jButtonKhaiBaoYTe.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonKhaiBaoYTe.setText("Khai báo y tế");
        jButtonKhaiBaoYTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKhaiBaoYTeActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelDaKhaiBao.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabelDaKhaiBao.setText("ĐÃ KHAI BÁO");

        jLabelSoKhaiBao.setBackground(new java.awt.Color(255, 255, 255));
        jLabelSoKhaiBao.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabelSoKhaiBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSoKhaiBao.setText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelDaKhaiBao)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelSoKhaiBao, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelDaKhaiBao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSoKhaiBao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextTimKiemMaNK, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTimKiem))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonKhaiBaoYTe, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTimKiemMaNK, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKhaiBaoYTe, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1067, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() throws SQLException, ClassNotFoundException {
        CovidHomeCtrl covidHomeCtrl = new CovidHomeCtrl();
        String daKhaiBao = covidHomeCtrl.getSoDaKhaiBao() +" / "+covidHomeCtrl.getTongNhanKhau();
        jLabelSoKhaiBao.setText(daKhaiBao);
        if (danhSach.getRowCount()>0) danhSach.setRowCount(0);
        KhaiBaoCtrl khaiBaoCtrl = new KhaiBaoCtrl();
        List<KhaiBaoBean> khaiBaoBeanList = khaiBaoCtrl.getAllKhaiBao();
        for (int i = 0; i<khaiBaoBeanList.size(); i++) {
            NhanKhau nhanKhau = khaiBaoBeanList.get(i).getNhanKhau();
            KhaiBao khaiBao = khaiBaoBeanList.get(i).getKhaiBao();

            int idToKhai = khaiBao.getId();
            String hoTen = nhanKhau.getHoTen();
            String gioiTinh = nhanKhau.getGioiTinh();
            String ngaySinh = nhanKhau.getNgaySinh();
            String ngayKhaiBao = khaiBao.getNgayKhaiBao();

            Object[] row = {idToKhai, hoTen, gioiTinh, ngaySinh, ngayKhaiBao};
            danhSach.addRow(row);
        }
    }
    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jTableKhaiBaoYTeMouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTableKhaiBaoYTeMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = jTableKhaiBaoYTe.getSelectedRow();
            int idToKhai = (int) danhSach.getValueAt(row, 0);
            ChiTietKhaiBaoView chiTietKhaiBaoView = new ChiTietKhaiBaoView(idToKhai);
            chiTietKhaiBaoView.setVisible(true);
        }

    }//GEN-LAST:event_jTableKhaiBaoYTeMouseClicked

    private void jTableKhaiBaoYTeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableKhaiBaoYTeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableKhaiBaoYTeMouseEntered

    private void jButtonKhaiBaoYTeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKhaiBaoYTeActionPerformed
        // TODO add your handling code here:
        KhaiBaoFormView khaiBaoFormView = new KhaiBaoFormView();
        khaiBaoFormView.setVisible(true);
    }//GEN-LAST:event_jButtonKhaiBaoYTeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonKhaiBaoYTe;
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDaKhaiBao;
    private javax.swing.JLabel jLabelSoKhaiBao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKhaiBaoYTe;
    private javax.swing.JTextField jTextTimKiemMaNK;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel danhSach;
}
