/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI.QuanLyCovid;

import com.nhom71_quanlyhokhau.UI.HomePanel;
import com.nhom71_quanlyhokhau.UI.QuanLyCovid.CachLyView.CachLyPanel;
import com.nhom71_quanlyhokhau.UI.QuanLyCovid.KhaiBaoYTeView.KhaiBaoYTePanel;
import com.nhom71_quanlyhokhau.UI.QuanLyCovid.TestCovidView.TestCovidHomePanel;


import javax.swing.*;

import java.awt.*;
import java.sql.SQLException;

/**
 *
 * @author nguyenduc
 */
public class CovidHomeView extends javax.swing.JFrame {

    /**
     * Creates new form CovidHomeView
     * @throws java.sql.SQLException
     * @throws java.lang.ClassNotFoundException
     */
    public CovidHomeView() throws SQLException, ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        CovidHomePanel covidHomePanel = new CovidHomePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(covidHomePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTrangChu = new javax.swing.JButton();
        jButtonKhaiBaoYTe = new javax.swing.JButton();
        jButtonCachLy = new javax.swing.JButton();
        jButtonThongKe = new javax.swing.JButton();
        jButtonTestCovid = new javax.swing.JButton();
        ParentPanel = new java.awt.Panel();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        setTitle("QUẢN LÝ COVID");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonTrangChu.setBackground(new java.awt.Color(255, 255, 204));
        jButtonTrangChu.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonTrangChu.setForeground(new java.awt.Color(102, 102, 255));
        jButtonTrangChu.setText("TRANG CHỦ");
        jButtonTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonTrangChuActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonKhaiBaoYTe.setBackground(new java.awt.Color(204, 255, 204));
        jButtonKhaiBaoYTe.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonKhaiBaoYTe.setText("KHAI BÁO Y TẾ");
        jButtonKhaiBaoYTe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonKhaiBaoYTeActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonCachLy.setBackground(new java.awt.Color(204, 255, 204));
        jButtonCachLy.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonCachLy.setText("CÁCH LY");
        jButtonCachLy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonCachLyActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThongKe.setBackground(new java.awt.Color(204, 255, 204));
        jButtonThongKe.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonThongKe.setText("THỐNG KÊ");
        jButtonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {

                try {
                    jButtonThongKeActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }

            }
        });

        jButtonTestCovid.setBackground(new java.awt.Color(204, 255, 204));
        jButtonTestCovid.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonTestCovid.setText("TEST COVID");
        jButtonTestCovid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonTestCovidActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonKhaiBaoYTe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCachLy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTestCovid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonKhaiBaoYTe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCachLy, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonTestCovid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 375, Short.MAX_VALUE))
        );

        ParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ParentPanel.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout ParentPanelLayout = new javax.swing.GroupLayout(ParentPanel);
        ParentPanel.setLayout(ParentPanelLayout);
        ParentPanelLayout.setHorizontalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1164, Short.MAX_VALUE)
        );
        ParentPanelLayout.setVerticalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrangChuActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonTrangChuActionPerformed
        // TODO add your handling code here:
        CovidHomePanel covidHomePanel = new CovidHomePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(covidHomePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonTrangChuActionPerformed

    private void jButtonKhaiBaoYTeActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonKhaiBaoYTeActionPerformed
        // TODO add your handling code here:
        KhaiBaoYTePanel khaiBaoYTePanel = new KhaiBaoYTePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(khaiBaoYTePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonKhaiBaoYTeActionPerformed

    private void jButtonCachLyActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonCachLyActionPerformed
        // TODO add your handling code here:
        CachLyPanel cachLyPanel = new CachLyPanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(cachLyPanel);
        ParentPanel.validate();
        ParentPanel.repaint();
        
    }//GEN-LAST:event_jButtonCachLyActionPerformed


    private void jButtonThongKeActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonThongKeActionPerformed

        // TODO add your handling code here:
        CovidThongKePanel covidThongKePanel = new CovidThongKePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(covidThongKePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonThongKeActionPerformed

    private void jButtonTestCovidActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonTestCovidActionPerformed
        // TODO add your handling code here:
        TestCovidHomePanel testCovidHomePanel = new TestCovidHomePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(testCovidHomePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonTestCovidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CovidHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CovidHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CovidHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CovidHomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CovidHomeView().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ParentPanel;
    private javax.swing.JButton jButtonCachLy;
    private javax.swing.JButton jButtonKhaiBaoYTe;
    private javax.swing.JButton jButtonTestCovid;
    private javax.swing.JButton jButtonThongKe;
    private javax.swing.JButton jButtonTrangChu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
