/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI;

import com.nhom71_quanlyhokhau.UI.HoKhauView.HoKhauHomeView;
import com.nhom71_quanlyhokhau.UI.NhanKhauView.NhanKhauHomeView;

import java.awt.*;
import java.sql.SQLException;

/**
 *
 * @author nguyenduc
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form HomeView
     */
    public HomeView() throws SQLException, ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        HomePanel homePanel = new HomePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(homePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTrangChu = new javax.swing.JButton();
        jButtonNhanKhau = new javax.swing.JButton();
        jButtonHoKhau = new javax.swing.JButton();
        jButtonThongKe = new javax.swing.JButton();
        ParentPanel = new java.awt.Panel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NHÓM 71- QUẢN LÝ NHÂN KHẨU");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButtonTrangChu.setBackground(new java.awt.Color(255, 255, 204));
        jButtonTrangChu.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonTrangChu.setForeground(new java.awt.Color(102, 102, 255));
        jButtonTrangChu.setText("TRANG CHỦ");
        jButtonTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonTrangChuActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonNhanKhau.setBackground(new java.awt.Color(204, 255, 204));
        jButtonNhanKhau.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonNhanKhau.setText("NHÂN KHẨU");
        jButtonNhanKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonNhanKhauActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonHoKhau.setBackground(new java.awt.Color(204, 255, 204));
        jButtonHoKhau.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonHoKhau.setText("HỘ KHẨU");
        jButtonHoKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonHoKhauActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThongKe.setBackground(new java.awt.Color(204, 255, 204));
        jButtonThongKe.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonThongKe.setText("THỐNG KÊ");
        jButtonThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonThongKeActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonNhanKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHoKhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonNhanKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonHoKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 427, Short.MAX_VALUE))
        );

        ParentPanel.setBackground(new java.awt.Color(255, 255, 255));
        ParentPanel.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout ParentPanelLayout = new javax.swing.GroupLayout(ParentPanel);
        ParentPanel.setLayout(ParentPanelLayout);
        ParentPanelLayout.setHorizontalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1156, Short.MAX_VALUE)
        );
        ParentPanelLayout.setVerticalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 713, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrangChuActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonTrangChuActionPerformed
        // TODO add your handling code here:
        HomePanel homePanel = new HomePanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(homePanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonTrangChuActionPerformed

    private void jButtonNhanKhauActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonNhanKhauActionPerformed
        // TODO add your handling code here:
        NhanKhauHomeView nhanKhauHomeView = new NhanKhauHomeView();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(nhanKhauHomeView);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonNhanKhauActionPerformed

    private void jButtonHoKhauActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonHoKhauActionPerformed
        // TODO add your handling code here:
        HoKhauHomeView hoKhauHomeView = new HoKhauHomeView();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(hoKhauHomeView);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonHoKhauActionPerformed

    private void jButtonThongKeActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonThongKeActionPerformed
        // TODO add your handling code here:
        ThongKeView thongKeView = new ThongKeView();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(thongKeView);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonThongKeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel ParentPanel;
    private javax.swing.JButton jButtonHoKhau;
    private javax.swing.JButton jButtonNhanKhau;
    private javax.swing.JButton jButtonThongKe;
    private javax.swing.JButton jButtonTrangChu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
