/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.nhom71_quanlyhokhau.UI;

import com.nhom71_quanlyhokhau.UI.NhanKhauView.ThongTinChiTietNhanKhau;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.QuanLyNhanKhauCtrl.NhanKhauCtrl;
import com.nhom71_quanlyhokhau.controllers.QuanLyNkHkCtrl.ThongKeCtrl;
import com.nhom71_quanlyhokhau.models.NhanKhau;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class ThongKeView extends javax.swing.JPanel {

    /**
     * Creates new form ThongKeView
     */
    public ThongKeView() throws SQLException, ClassNotFoundException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();
        jComboGioiTinh = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jComboLoai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextTuoi1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextTuoi2 = new javax.swing.JTextField();
        jButtonTimKiem = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSach = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel.setText("Giới tính:");

        jComboGioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả", "Nam", "Nữ"}));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Loại:");

        jComboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Tất cả", "Chính thức", "Tạm trú", "Tạm vắng"}));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Độ tuổi:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("=>");

        jButtonTimKiem.setBackground(new java.awt.Color(255, 255, 153));
        jButtonTimKiem.setText("Tìm kiếm");
        jButtonTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonTimKiemActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jTableDanhSach.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTableDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
                new String [] {
                        "ID", "Họ tên", "Giới tính", "Ngày sinh", "Địa chỉ"
                }
        ));
        danhsachnhankhau = (DefaultTableModel) jTableDanhSach.getModel();
        TableCellEditor nonEditableCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhsachnhankhau.getColumnCount(); column++) {
            TableColumn tableColumn = jTableDanhSach.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor);
        }
        jTableDanhSach.setToolTipText("");
        jTableDanhSach.setEnabled(false);
        jTableDanhSach.setRowHeight(30);
        jTableDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTableDanhSachMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableDanhSachMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDanhSach);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextTuoi1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jTextTuoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboGioiTinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)
                        .addComponent(jLabel1)
                        .addGap(113, 113, 113)
                        .addComponent(jComboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonTimKiem))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1081, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel)
                            .addComponent(jComboGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextTuoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextTuoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() throws SQLException, ClassNotFoundException {
        jTextTuoi1.setText("-1");
        jTextTuoi2.setText("-1");

        if (danhsachnhankhau.getRowCount()>0) danhsachnhankhau.setRowCount(0);
        NhanKhauCtrl nhanKhauCtrl = new NhanKhauCtrl();
        List<NhanKhau> nhanKhauList = nhanKhauCtrl.getDanhSachNhanKhau();

        for (int i = 0; i<nhanKhauList.size(); i++) {
            int id = nhanKhauList.get(i).getId();
            String hoTen = nhanKhauList.get(i).getHoTen();
            String ngaySinh = nhanKhauList.get(i).getNgaySinh();
            String gioiTinh = nhanKhauList.get(i).getGioiTinh();
            String diaChi = nhanKhauList.get(i).getDiaChiHienTai();

            Object[] row = {id, hoTen, gioiTinh, ngaySinh, diaChi};
            danhsachnhankhau.addRow(row);
        }
    }
    private void jButtonTimKiemActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonTimKiemActionPerformed
        // TODO add your handling code here:
        String gioiTinh = (String) jComboGioiTinh.getSelectedItem();
        String loai = (String) jComboLoai.getSelectedItem();
        int doTuoiTu = Integer.parseInt(jTextTuoi1.getText());
        int doTuoiDen = Integer.parseInt(jTextTuoi2.getText());

        ThongKeCtrl thongKeCtrl = new ThongKeCtrl();
        List<NhanKhau> nhanKhauList = thongKeCtrl.locNhanKhau(gioiTinh, loai, doTuoiTu, doTuoiDen);
        if (danhsachnhankhau.getRowCount()>0) danhsachnhankhau.setRowCount(0);
        for (int i = 0; i<nhanKhauList.size(); i++) {
            int idn = nhanKhauList.get(i).getId();
            String hoTenn = nhanKhauList.get(i).getHoTen();
            String ngaySinhn = nhanKhauList.get(i).getNgaySinh();
            String gioiTinhn = nhanKhauList.get(i).getGioiTinh();
            String diaChin = nhanKhauList.get(i).getDiaChiHienTai();

            Object[] row = {idn, hoTenn, gioiTinhn, ngaySinhn, diaChin};
            danhsachnhankhau.addRow(row);
        }

    }//GEN-LAST:event_jButtonTimKiemActionPerformed

    private void jTableDanhSachMouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTableDanhSachMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            int row = jTableDanhSach.getSelectedRow();
            int IdNhanKhau = (int) jTableDanhSach.getValueAt(row, 0);
            System.out.println(IdNhanKhau);
            ThongTinChiTietNhanKhau thongTinChiTietNhanKhau = new ThongTinChiTietNhanKhau(IdNhanKhau);
            thongTinChiTietNhanKhau.setVisible(true);
        }
    }//GEN-LAST:event_jTableDanhSachMouseClicked

    private void jTableDanhSachMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDanhSachMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTimKiem;
    private javax.swing.JComboBox<String> jComboGioiTinh;
    private javax.swing.JComboBox<String> jComboLoai;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableDanhSach;
    private javax.swing.JTextField jTextTuoi1;
    private javax.swing.JTextField jTextTuoi2;
    // End of variables declaration//GEN-END:variables
    DefaultTableModel danhsachnhankhau;
}
